# Только обязательные параметры
- id: 1
  label: Button
# Обязательные и необязательные
- id: two
  label: Кнопка
  link: https://bash.im
# Есть родитель, но нет ссылки
- id: три
  label: Есть родитель со ссылкой
  depends: two
# Все (родитель в списке и у него нет ссылки)
- id: 555
  label: 1234
  link: https://bash.im
  depends: 1
# Все (родитель в списке, ссылки идентичны с родительской)
- id: 4
  label: Ссылка идентична родителю
  link: https://bash.im
  depends: two
# Все(родитель в списке, ссылка отличается от родительской)
- id: \@#
  label: \@#
  link: https://www.petshop.ru
  depends: two